"""Initial migration

Revision ID: 981d1e025fa9
Revises: 48391502a3a3
Create Date: 2024-11-09 12:12:29.856882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981d1e025fa9'
down_revision = '48391502a3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
